# Generated by Django 5.2.6 on 2025-11-07 14:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría (ej: Resinas, Anestésicos)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si la categoría está activa')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría Insumo',
                'verbose_name_plural': 'Categorías Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del insumo (SKU)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del insumo/material', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del insumo', null=True)),
                ('precio_costo', models.DecimalField(decimal_places=2, help_text='Precio de costo del insumo', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio de venta del insumo (al incluirlo en un tratamiento)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad actual en stock', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad mínima antes de alertar', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unidad_medida', models.CharField(default='unidad', help_text='Unidad de medida (unidad, caja, ml, g, etc.)', max_length=20)),
                ('proveedor', models.CharField(blank=True, help_text='Nombre del proveedor principal', max_length=200, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si el insumo está activo para ser usado')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece el insumo', on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='inventario.categoriainsumo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='inventario__codigo_9db44a_idx'), models.Index(fields=['categoria', 'activo'], name='inventario__categor_f5d4e5_idx')],
            },
        ),
    ]
