# Generated by Django 5.2.6 on 2025-11-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('motivo', models.TextField(verbose_name='Motivo de la consulta')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la cita', verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_atendidas', to='usuarios.perfilodontologo', verbose_name='Odontólogo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='usuarios.perfilpaciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Agenda',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='agenda_cita_fecha_h_7504f2_idx'), models.Index(fields=['estado'], name='agenda_cita_estado_a9a647_idx')],
            },
        ),
    ]
