# Generated by Django 5.2.6 on 2025-11-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('tratamientos', '0004_presupuesto_itempresupuesto_and_more'),
        ('usuarios', '0003_usuario_ci_usuario_sexo_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='item_plan',
            field=models.ForeignKey(blank=True, help_text='Si es cita de tratamiento, vincula con el ítem específico del plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_asociada', to='tratamientos.itemplantratamiento', verbose_name='Ítem del Plan'),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo_tipo',
            field=models.CharField(choices=[('CONSULTA', 'Consulta General'), ('URGENCIA', 'Urgencia/Dolor'), ('LIMPIEZA', 'Limpieza Dental'), ('REVISION', 'Revisión/Control'), ('PLAN', 'Tratamiento de mi Plan')], default='CONSULTA', help_text='Determina el costo de la cita', max_length=20, verbose_name='Tipo de Motivo'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.TextField(help_text='Descripción detallada del motivo', verbose_name='Motivo de la consulta'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['motivo_tipo'], name='agenda_cita_motivo__6ca894_idx'),
        ),
    ]
