# Generated by Django 5.2.6 on 2025-11-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_cita_item_plan_cita_motivo_tipo_alter_cita_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='pagada',
            field=models.BooleanField(default=False, help_text='Indica si la cita ha sido pagada', verbose_name='Pagada'),
        ),
    ]
