# Generated by Django 5.2.6 on 2025-11-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PRUEBA', 'Prueba (7 días gratis)'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en USD', max_digits=10)),
                ('duracion_dias', models.IntegerField(help_text='Duración del plan en días')),
                ('max_usuarios', models.IntegerField(default=10, help_text='Máximo de usuarios permitidos')),
                ('max_pacientes', models.IntegerField(default=500, help_text='Máximo de pacientes permitidos')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['precio'],
            },
        ),
        migrations.AddField(
            model_name='clinica',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clinica',
            name='direccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clinica',
            name='email_admin',
            field=models.EmailField(blank=True, default='', help_text='Email del administrador de la clínica', max_length=254),
        ),
        migrations.AddField(
            model_name='clinica',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida por Pago'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='clinica',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas internas del administrador'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='pais',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clinica',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='activo',
            field=models.BooleanField(default=False, help_text='Activo en el sistema'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinicas', to='tenants.plansuscripcion'),
        ),
        migrations.CreateModel(
            name='SolicitudRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clinica', models.CharField(max_length=200)),
                ('dominio_deseado', models.CharField(help_text="Subdominio deseado (ej: 'miclinica' para miclinica.ejemplo.com)", max_length=200, unique=True)),
                ('nombre_contacto', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('mensaje', models.TextField(blank=True, help_text='Mensaje o comentarios adicionales del solicitante')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('PROCESADA', 'Procesada (Clínica Creada)')], default='PENDIENTE', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('revisada', models.DateTimeField(blank=True, null=True)),
                ('procesada', models.DateTimeField(blank=True, null=True)),
                ('clinica_creada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='tenants.clinica')),
                ('plan_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='tenants.plansuscripcion')),
            ],
            options={
                'verbose_name': 'Solicitud de Registro',
                'verbose_name_plural': 'Solicitudes de Registro',
                'ordering': ['-creada'],
            },
        ),
    ]
