# Generated by Django 5.2.6 on 2025-11-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_plansuscripcion_clinica_actualizado_clinica_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='backup_day_of_month',
            field=models.IntegerField(blank=True, help_text='Día del mes para backups mensuales (1-28)', null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='backup_schedule',
            field=models.CharField(choices=[('disabled', 'Desactivado'), ('daily', 'Diario'), ('every_12h', 'Cada 12 horas'), ('every_6h', 'Cada 6 horas'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('scheduled', 'Programado (Fecha específica)')], default='disabled', help_text='Frecuencia de los backups automáticos', max_length=20),
        ),
        migrations.AddField(
            model_name='clinica',
            name='backup_time',
            field=models.TimeField(blank=True, help_text='Hora específica para backups (ej: 02:00 AM para diarios/semanales/mensuales)', null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='backup_weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana para backups semanales (0=Lunes, 6=Domingo)', null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='last_backup_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del último backup automático exitoso', null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='next_scheduled_backup',
            field=models.DateTimeField(blank=True, help_text="Fecha y hora exacta programada para el próximo backup (solo para 'scheduled')", null=True),
        ),
    ]
