# Generated by Django 5.2.6 on 2025-11-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_clinica_backup_day_of_month_clinica_backup_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudregistro',
            name='credenciales_descargadas',
            field=models.BooleanField(default=False, help_text='Indica si el cliente ya descargó el archivo de credenciales'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='datos_pago',
            field=models.JSONField(blank=True, default=dict, help_text='Datos adicionales de la transacción (JSON)'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='fecha_descarga_credenciales',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('MERCADOPAGO', 'MercadoPago'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('OTRO', 'Otro')], help_text='Método de pago utilizado', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto pagado en USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='pago_exitoso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='password_admin_generado',
            field=models.CharField(blank=True, help_text='Contraseña temporal generada (se limpia después de la entrega)', max_length=255),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='token_descarga',
            field=models.CharField(blank=True, help_text='Token único para descargar credenciales (válido 24h)', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='token_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='transaccion_id',
            field=models.CharField(blank=True, help_text='ID de transacción de la pasarela de pago', max_length=255),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='usuario_admin_generado',
            field=models.CharField(blank=True, help_text='Email/usuario del administrador generado automáticamente', max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitudregistro',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGO_PROCESANDO', 'Procesando Pago'), ('PAGO_EXITOSO', 'Pago Exitoso - Creando Clínica'), ('COMPLETADA', 'Completada (Clínica Creada)'), ('PAGO_FALLIDO', 'Pago Fallido'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_PAGO', max_length=20),
        ),
    ]
