# Generated by Django 5.2.6 on 2025-11-07 14:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría (ej: Odontología General, Ortodoncia)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si la categoría está activa')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización en listas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_servicio', models.CharField(help_text='Código único del servicio (ej: CONS-001, REST-001)', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del servicio odontológico', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del procedimiento', null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Honorarios base del servicio (sin materiales)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tiempo_estimado', models.PositiveIntegerField(default=30, help_text='Tiempo estimado del procedimiento en minutos')),
                ('requiere_cita_previa', models.BooleanField(default=True, help_text='Si el servicio requiere cita programada')),
                ('requiere_autorizacion', models.BooleanField(default=False, help_text='Si requiere autorización especial (ej: cirugías)')),
                ('activo', models.BooleanField(default=True, help_text='Si el servicio está disponible para ser ofrecido')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas para uso interno del personal', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece el servicio', on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='tratamientos.categoriaservicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Catálogo de Servicios',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['codigo_servicio'], name='tratamiento_codigo__d72a71_idx'), models.Index(fields=['categoria', 'activo'], name='tratamiento_categor_07a095_idx'), models.Index(fields=['activo'], name='tratamiento_activo_71f2b5_idx')],
            },
        ),
    ]
