# Generated by Django 5.2.6 on 2025-11-07 14:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialServicioFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1.0, help_text='Cantidad del insumo requerida', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('es_obligatorio', models.BooleanField(default=True, help_text='Si este material es obligatorio para el servicio')),
                ('notas', models.TextField(blank=True, help_text='Notas sobre el uso de este material', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(help_text='Insumo específico que se usa', on_delete=django.db.models.deletion.PROTECT, related_name='servicios_fijos', to='inventario.insumo')),
                ('servicio', models.ForeignKey(help_text='Servicio que requiere este material', on_delete=django.db.models.deletion.CASCADE, related_name='materiales_fijos', to='tratamientos.servicio')),
            ],
            options={
                'verbose_name': 'Material Fijo de Servicio',
                'verbose_name_plural': 'Materiales Fijos de Servicio',
                'indexes': [models.Index(fields=['servicio', 'es_obligatorio'], name='tratamiento_servici_4e18fb_idx')],
                'unique_together': {('servicio', 'insumo')},
            },
        ),
        migrations.CreateModel(
            name='MaterialServicioOpcional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1.0, help_text='Cantidad requerida del insumo elegido', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('es_obligatorio', models.BooleanField(default=True, help_text='Si es obligatorio elegir un material de esta categoría')),
                ('nombre_personalizado', models.CharField(blank=True, help_text="Nombre descriptivo para mostrar al usuario (ej: 'Tipo de Resina')", max_length=100, null=True)),
                ('notas', models.TextField(blank=True, help_text='Instrucciones o notas sobre la selección', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria_insumo', models.ForeignKey(help_text='Categoría de insumos entre los que se puede elegir', on_delete=django.db.models.deletion.PROTECT, related_name='servicios_opcionales', to='inventario.categoriainsumo')),
                ('servicio', models.ForeignKey(help_text='Servicio que requiere elegir un material', on_delete=django.db.models.deletion.CASCADE, related_name='materiales_opcionales', to='tratamientos.servicio')),
            ],
            options={
                'verbose_name': 'Material Opcional de Servicio',
                'verbose_name_plural': 'Materiales Opcionales de Servicio',
                'indexes': [models.Index(fields=['servicio', 'es_obligatorio'], name='tratamiento_servici_6a3bd2_idx')],
                'unique_together': {('servicio', 'categoria_insumo')},
            },
        ),
    ]
