# Generated by Django 5.2.6 on 2025-11-07 14:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('tratamientos', '0002_materialserviciofijo_materialservicioopcional'),
        ('usuarios', '0002_especialidad_alter_perfilodontologo_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDeTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Título descriptivo del plan (ej: 'Rehabilitación Dental Completa')", max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del plan de tratamiento', null=True)),
                ('estado', models.CharField(choices=[('PROPUESTO', 'Propuesto'), ('PRESENTADO', 'Presentado al paciente'), ('ACEPTADO', 'Aceptado por el paciente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PROPUESTO', help_text='Estado actual del plan', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_presentacion', models.DateTimeField(blank=True, help_text='Fecha en que se presentó el plan al paciente', null=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, help_text='Fecha en que el paciente aceptó el plan', null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha de inicio de los tratamientos', null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, help_text='Fecha de finalización de todos los tratamientos', null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', help_text='Prioridad del plan de tratamiento', max_length=20)),
                ('notas_internas', models.TextField(blank=True, help_text='Notas internas para el equipo médico', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('odontologo', models.ForeignKey(help_text='Odontólogo que crea el plan', on_delete=django.db.models.deletion.PROTECT, related_name='planes_creados', to='usuarios.perfilodontologo')),
                ('paciente', models.ForeignKey(help_text='Paciente para quien se crea el plan', on_delete=django.db.models.deletion.CASCADE, related_name='planes_tratamiento', to='usuarios.perfilpaciente')),
            ],
            options={
                'verbose_name': 'Plan de Tratamiento',
                'verbose_name_plural': 'Planes de Tratamiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemPlanTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_servicio_snapshot', models.DecimalField(decimal_places=2, help_text='Precio base del servicio al momento de crear el ítem', max_digits=10)),
                ('precio_materiales_fijos_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo de materiales fijos al momento de crear el ítem', max_digits=10)),
                ('precio_insumo_seleccionado_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio del insumo seleccionado al momento de crear el ítem', max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', help_text='Estado de este ítem específico', max_length=20)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de ejecución de este ítem en el plan')),
                ('notas', models.TextField(blank=True, help_text='Notas específicas para este ítem', null=True)),
                ('fecha_estimada', models.DateField(blank=True, help_text='Fecha estimada para realizar este tratamiento', null=True)),
                ('fecha_realizada', models.DateTimeField(blank=True, help_text='Fecha en que se realizó el tratamiento', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('insumo_seleccionado', models.ForeignKey(blank=True, help_text='Insumo específico elegido para materiales opcionales', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_donde_usado', to='inventario.insumo')),
                ('servicio', models.ForeignKey(help_text='Servicio a realizar', on_delete=django.db.models.deletion.PROTECT, related_name='items_plan', to='tratamientos.servicio')),
                ('plan', models.ForeignKey(help_text='Plan de tratamiento al que pertenece este ítem', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tratamientos.plandetratamiento')),
            ],
            options={
                'verbose_name': 'Ítem Plan Tratamiento',
                'verbose_name_plural': 'Ítems Plan Tratamiento',
                'ordering': ['plan', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='plandetratamiento',
            index=models.Index(fields=['paciente', 'estado'], name='tratamiento_pacient_d2ab13_idx'),
        ),
        migrations.AddIndex(
            model_name='plandetratamiento',
            index=models.Index(fields=['odontologo', 'fecha_creacion'], name='tratamiento_odontol_ca1395_idx'),
        ),
        migrations.AddIndex(
            model_name='plandetratamiento',
            index=models.Index(fields=['estado', 'prioridad'], name='tratamiento_estado_f9a84c_idx'),
        ),
        migrations.AddIndex(
            model_name='itemplantratamiento',
            index=models.Index(fields=['plan', 'orden'], name='tratamiento_plan_id_89604b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemplantratamiento',
            index=models.Index(fields=['estado'], name='tratamiento_estado_5aaba1_idx'),
        ),
    ]
