# Generated by Django 5.2.6 on 2025-11-07 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0003_plandetratamiento_itemplantratamiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versión del presupuesto para este plan (permite múltiples versiones)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PRESENTADO', 'Presentado'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('VENCIDO', 'Vencido')], default='BORRADOR', help_text='Estado actual del presupuesto', max_length=20)),
                ('subtotal_servicios', models.DecimalField(decimal_places=2, default=0, help_text='Total de todos los servicios base', max_digits=10)),
                ('subtotal_materiales_fijos', models.DecimalField(decimal_places=2, default=0, help_text='Total de materiales fijos incluidos', max_digits=10)),
                ('subtotal_materiales_opcionales', models.DecimalField(decimal_places=2, default=0, help_text='Total de materiales opcionales seleccionados', max_digits=10)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, help_text='Descuentos aplicados (si los hay)', max_digits=10)),
                ('total_presupuestado', models.DecimalField(decimal_places=2, default=0, help_text='Precio total final del presupuesto', max_digits=10)),
                ('fecha_presentacion', models.DateTimeField(blank=True, help_text='Cuándo se presentó el presupuesto al paciente', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha límite para aceptar el presupuesto', null=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, help_text='Cuándo el paciente aceptó el presupuesto', null=True)),
                ('token_aceptacion', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para que el paciente pueda aceptar sin login', unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('plan_tratamiento', models.ForeignKey(help_text='Plan de tratamiento del cual se genera este presupuesto', on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='tratamientos.plandetratamiento')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-fecha_presentacion', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden del ítem en el presupuesto')),
                ('nombre_servicio', models.CharField(help_text='Nombre del servicio (snapshot)', max_length=200)),
                ('nombre_insumo_seleccionado', models.CharField(blank=True, help_text='Nombre del material seleccionado (snapshot)', max_length=200, null=True)),
                ('precio_servicio', models.DecimalField(decimal_places=2, help_text='Precio del servicio base (congelado)', max_digits=10)),
                ('precio_materiales_fijos', models.DecimalField(decimal_places=2, help_text='Precio de materiales fijos (congelado)', max_digits=10)),
                ('precio_insumo_seleccionado', models.DecimalField(decimal_places=2, help_text='Precio del material opcional (congelado)', max_digits=10)),
                ('precio_total_item', models.DecimalField(decimal_places=2, help_text='Precio total del ítem (congelado)', max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('item_plan_original', models.ForeignKey(blank=True, help_text='Ítem original del plan (referencia)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_presupuesto', to='tratamientos.itemplantratamiento')),
                ('presupuesto', models.ForeignKey(help_text='Presupuesto al que pertenece este ítem', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tratamientos.presupuesto')),
            ],
            options={
                'verbose_name': 'Ítem de Presupuesto',
                'verbose_name_plural': 'Ítems de Presupuesto',
                'ordering': ['orden'],
            },
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['plan_tratamiento', 'estado'], name='tratamiento_plan_tr_958627_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['fecha_vencimiento', 'estado'], name='tratamiento_fecha_v_ed1d62_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['token_aceptacion'], name='tratamiento_token_a_7b5b7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together={('plan_tratamiento', 'version')},
        ),
        migrations.AddIndex(
            model_name='itempresupuesto',
            index=models.Index(fields=['presupuesto', 'orden'], name='tratamiento_presupu_312170_idx'),
        ),
    ]
