# Generated by Django 5.2.6 on 2025-11-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0004_presupuesto_itempresupuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetratamiento',
            name='estado',
            field=models.CharField(choices=[('propuesto', 'Propuesto'), ('presentado', 'Presentado al paciente'), ('aceptado', 'Aceptado por el paciente'), ('aprobado', 'Aprobado por el paciente'), ('rechazado', 'Rechazado por el paciente'), ('en_progreso', 'En progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='propuesto', help_text='Estado actual del plan', max_length=20),
        ),
    ]
