"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8xyx^asm1uqoy7on4b(y2%e)o@)wf=fh%og*hfpbe+uiqe5tkp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# --- django-tenants requires splitting apps into SHARED_APPS and TENANT_APPS.
# See docs: https://django-tenants.readthedocs.io/

# Shared apps live in the public schema (ej. admin / Super-Admin site)
SHARED_APPS = [
    'django_tenants',          # django-tenants core
    'tenants',                 # app to manage tenants (we'll create it)

    # Django contrib apps used in public
    # NOTE: We do NOT include django.contrib.admin here because admin depends on
    # AUTH_USER_MODEL which is tenant-only. The public admin uses a custom AdminSite.
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party used in public
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
]

# Tenant apps are installed into each tenant schema
TENANT_APPS = [
    # Django contrib apps that tenant needs
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',

    # --- Mis Aplicaciones (instaladas por tenant) ---
    'usuarios',  # Usuario DEBE estar en TENANT_APPS
    'agenda',
    'historial_clinico',
    'tratamientos',
    'facturacion',
    'inventario',
    'reportes',

    # Third-party for tenant runtime
    'rest_framework',
]

# Combine into INSTALLED_APPS (keep order: SHARED_APPS first)
INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Tenant middleware must run after session middleware and before common
    'django_tenants.middleware.TenantMainMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================================
# URL ROUTING CONFIGURATION (django-tenants)
# ============================================================
# ROOT_URLCONF: Used by django-tenants for TENANT schemas (clinic subdomains)
# PUBLIC_SCHEMA_URLCONF: Used for the PUBLIC schema (localhost)
#
# This separation allows different admin sites:
# - localhost → public_admin_site (manages Clinicas, Domains)
# - clinica-demo.localhost → standard admin.site (manages Usuarios, Agenda, etc.)
ROOT_URLCONF = 'core.urls_tenant'           # For tenant schemas
PUBLIC_SCHEMA_URLCONF = 'core.urls_public'  # For public schema (localhost)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add custom templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL with django-tenants for multi-tenant schemas.
# Development DB settings (Postgres via Docker). Credentials per request:
DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'db_clinica_multitenant',
        'USER': 'postgres',
        'PASSWORD': '12345678',
        'HOST': '127.0.0.1',
        'PORT': '5432',
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}

# Database router required by django-tenants (keeps migrations in sync)
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# --- Configuración de CORS ---

# Orígenes (servidores de frontend) que tienen permiso para hacer peticiones
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Puerto por defecto de Vite (React)
    "http://localhost:3000",  # Puerto por defecto de Create-React-App
]

# --- Configuración de CSRF ---

# Orígenes en los que confiamos para peticiones POST (como el login)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Configuración de Django REST Framework (DRF) ---

REST_FRAMEWORK = {
    # Por defecto, todas las vistas requerirán que el usuario esté autenticado.
    # Haremos excepciones manuales para 'Login' y 'Registro'.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    # Configura la autenticación usando JWT (JSON Web Tokens)
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# django-tenants: indicar el modelo Tenant y Domain (app_name.ModelName)
TENANT_MODEL = "tenants.Clinica"
TENANT_DOMAIN_MODEL = "tenants.Domain"

# --- Configuración del Modelo de Autenticación ---
# Le dice a Django que use nuestro modelo 'Usuario' de la app 'usuarios'
AUTH_USER_MODEL = 'usuarios.Usuario'
