"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-8xyx^asm1uqoy7on4b(y2%e)o@)wf=fh%og*hfpbe+uiqe5tkp')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Hosts permitidos
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,.localhost,127.0.0.1', cast=Csv())

# Si estamos en producción, agregar el dominio de Render
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    ALLOWED_HOSTS.append(f'.{RENDER_EXTERNAL_HOSTNAME}')  # Para subdominios

# Permitir subdominios de onrender.com para multi-tenant
if not DEBUG:
    ALLOWED_HOSTS.append('.onrender.com')  # Permite *.onrender.com


# Application definition

# --- django-tenants requires splitting apps into SHARED_APPS and TENANT_APPS.
# See docs: https://django-tenants.readthedocs.io/

# Shared apps live in the public schema (ej. admin / Super-Admin site)
SHARED_APPS = [
    'django_tenants',          # django-tenants core
    'tenants',                 # app to manage tenants (we'll create it)

    # Django contrib apps used in public
    # NOTE: We do NOT include django.contrib.admin here because admin depends on
    # AUTH_USER_MODEL which is tenant-only. The public admin uses a custom AdminSite.
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party used in public
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
]

# Tenant apps are installed into each tenant schema
TENANT_APPS = [
    # Django contrib apps that tenant needs
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',

    # --- Mis Aplicaciones (instaladas por tenant) ---
    'usuarios',  # Usuario DEBE estar en TENANT_APPS
    'agenda',
    'historial_clinico',
    'tratamientos',
    'facturacion',
    'inventario',
    'reportes',
    'backups',  # Sistema de backups automáticos

    # Third-party for tenant runtime
    'rest_framework',
]

# Combine into INSTALLED_APPS (keep order: SHARED_APPS first)
INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Tenant middleware must run after session middleware and before common
    'django_tenants.middleware.TenantMainMiddleware',
    # Custom middleware para forzar tenant por defecto en dominio público
    'core.middleware.DefaultTenantMiddleware',
    'core.middleware_mobile.MobileAppMiddleware',  # ✅ Permitir apps móviles
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================================
# URL ROUTING CONFIGURATION (django-tenants)
# ============================================================
# ROOT_URLCONF: Used by django-tenants for TENANT schemas (clinic subdomains)
# PUBLIC_SCHEMA_URLCONF: Used for the PUBLIC schema (localhost)
#
# This separation allows different admin sites:
# - localhost → public_admin_site (manages Clinicas, Domains)
# - clinica-demo.localhost → standard admin.site (manages Usuarios, Agenda, etc.)
ROOT_URLCONF = 'core.urls_tenant'           # For tenant schemas
PUBLIC_SCHEMA_URLCONF = 'core.urls_public'  # For public schema (localhost)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add custom templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL with django-tenants for multi-tenant schemas.
# Configuración de base de datos con soporte para DATABASE_URL (Render)
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Producción: Usar DATABASE_URL de Render
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            engine='django_tenants.postgresql_backend',
        )
    }
else:
    # Desarrollo: Usar configuración local
    DATABASES = {
        'default': {
            'ENGINE': 'django_tenants.postgresql_backend',
            'NAME': config('DB_NAME', default='db_clinica_multitenant'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default='12345678'),
            'HOST': config('DB_HOST', default='127.0.0.1'),
            'PORT': config('DB_PORT', default='5432'),
            'OPTIONS': {
                'client_encoding': 'UTF8',
            },
        }
    }

# Database router required by django-tenants (keeps migrations in sync)
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configuración de WhiteNoise para servir archivos estáticos en producción
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    # Agregar WhiteNoise al middleware
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

# Archivos de media (uploads de usuarios)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuración de email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Desarrollo: imprime en consola
DEFAULT_FROM_EMAIL = 'noreply@clinica-dental.com'
SERVER_EMAIL = 'admin@clinica-dental.com'

# --- Configuración de CORS ---

# Orígenes (servidores de frontend) que tienen permiso para hacer peticiones
cors_origins = config('CORS_ALLOWED_ORIGINS', default='http://localhost:5173,http://localhost:3000', cast=Csv())
CORS_ALLOWED_ORIGINS = list(cors_origins)

# ✅ Para apps móviles: Permitir CUALQUIER origen
# Esto es necesario porque las apps móviles no tienen un "origin" fijo
if not DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True  # Permitir apps móviles en producción

# Permitir subdominios para multi-tenant
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://[\w-]+\.localhost:\d+$",   # Desarrollo: *.localhost:puerto
    r"^https://[\w-]+\.onrender\.com$",  # Producción: *.onrender.com
    r"^https://[\w-]+\.vercel\.app$",    # Frontend Vercel: *.vercel.app
    r"^https://[\w-]+\.netlify\.app$",   # Frontend Netlify: *.netlify.app
    r"^https://.*\.dentaabcxy\.store$",  # Frontend custom domain: *.dentaabcxy.store
    r"^https://dentaabcxy\.store$",      # Frontend custom domain: dentaabcxy.store (sin www)
]

# Permitir envío de cookies y credenciales (necesario para JWT)
CORS_ALLOW_CREDENTIALS = True

# Permitir headers específicos (necesarios para JWT y multi-tenant)
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-tenant-id',  # Para multi-tenant con subdominios
    'host',  # ✅ Para apps móviles (Header Host)
    'x-mobile-app',  # ✅ Para identificar apps móviles
]

# --- Configuración de CSRF ---

# Orígenes en los que confiamos para peticiones POST (como el login)
csrf_trusted = config('CSRF_TRUSTED_ORIGINS', default='http://localhost:5173,http://localhost:3000', cast=Csv())
CSRF_TRUSTED_ORIGINS = list(csrf_trusted)

# Agregar el dominio de Render si existe
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# En producción, permitir subdominios de Render y plataformas de frontend
if not DEBUG:
    # Render permite wildcards con https://*.dominio.com
    CSRF_TRUSTED_ORIGINS.extend([
        'https://*.onrender.com',
        'https://*.vercel.app',
        'https://*.netlify.app',
    ])

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Configuración de Django REST Framework (DRF) ---

REST_FRAMEWORK = {
    # Por defecto, todas las vistas requerirán que el usuario esté autenticado.
    # Haremos excepciones manuales para 'Login' y 'Registro'.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    # Configura la autenticación usando JWT (JSON Web Tokens)
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# --- Configuración de Simple JWT ---
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # Token de acceso dura 1 hora (en vez de 5 minutos)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh token dura 7 días
    'ROTATE_REFRESH_TOKENS': False,  # No rotar refresh tokens automáticamente
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# django-tenants: indicar el modelo Tenant y Domain (app_name.ModelName)
TENANT_MODEL = "tenants.Clinica"
TENANT_DOMAIN_MODEL = "tenants.Domain"

# --- Configuración del Modelo de Autenticación ---
# Le dice a Django que use nuestro modelo 'Usuario' de la app 'usuarios'
AUTH_USER_MODEL = 'usuarios.Usuario'

# ============================================================================
# CONFIGURACIÓN DE SUPABASE (BACKUPS)
# ============================================================================
SUPABASE_URL = config('SUPABASE_URL', default='')
SUPABASE_KEY = config('SUPABASE_KEY', default='')

# --- Configuración de Logging ---
# Para poder ver errores detallados en producción (Render)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',  # Loguear errores 500
            'propagate': False,
        },
        'reportes': {
            'handlers': ['console'],
            'level': 'ERROR',  # Loguear errores en la app reportes
            'propagate': False,
        },
    },
}
