# Generated by Django 5.2.6 on 2025-11-07 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tratamientos', '0004_presupuesto_itempresupuesto_and_more'),
        ('usuarios', '0003_usuario_ci_usuario_sexo_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_ci', models.CharField(blank=True, help_text='NIT o CI para la facturación', max_length=50, null=True, verbose_name='NIT/CI')),
                ('razon_social', models.CharField(blank=True, help_text='Nombre o razón social para la factura', max_length=255, null=True, verbose_name='Razón Social')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total de la factura', max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, help_text='Monto pagado hasta el momento', max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', help_text='Estado actual de la factura', max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='usuarios.perfilpaciente')),
                ('presupuesto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura', to='tratamientos.presupuesto')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, help_text='Monto de este pago específico', max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('QR', 'Pago QR'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='EFECTIVO', help_text='Método utilizado para el pago', max_length=20)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', help_text='Estado actual del pago', max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('referencia_transaccion', models.CharField(blank=True, help_text='ID de transacción, Nro. de cheque, etc.', max_length=255, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el pago', null=True)),
                ('factura', models.ForeignKey(help_text='Factura a la que se aplica este pago', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura')),
                ('paciente', models.ForeignKey(help_text='Paciente que realiza el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_realizados', to='usuarios.perfilpaciente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
