# Generated by Django 5.2.6 on 2025-11-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_cita_pagada'),
        ('facturacion', '0001_initial'),
        ('tratamientos', '0005_alter_plandetratamiento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cita',
            field=models.ForeignKey(blank=True, help_text='Cita relacionada con este pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='agenda.cita'),
        ),
        migrations.AddField(
            model_name='pago',
            name='datos_pago',
            field=models.JSONField(blank=True, default=dict, help_text='Datos completos de la transacción de la pasarela'),
        ),
        migrations.AddField(
            model_name='pago',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción del pago', max_length=500),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se completó el pago', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='ID de la intención de pago (Stripe payment_intent)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='plan_tratamiento',
            field=models.ForeignKey(blank=True, help_text='Plan de tratamiento relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='tratamientos.plandetratamiento'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('FACTURA', 'Pago de Factura'), ('CITA', 'Pago de Cita'), ('TRATAMIENTO', 'Pago de Tratamiento'), ('PLAN', 'Pago de Plan de Tratamiento'), ('OTRO', 'Otro')], default='FACTURA', help_text='Tipo de pago realizado', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='transaccion_id',
            field=models.CharField(blank=True, help_text='ID de la sesión de checkout (Stripe session_id, PayPal order_id, etc.)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', help_text='Estado actual del pago', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(blank=True, help_text='Factura a la que se aplica este pago', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('QR', 'Pago QR'), ('CHEQUE', 'Cheque'), ('STRIPE', 'Stripe (Tarjeta Online)'), ('PAYPAL', 'PayPal'), ('MERCADOPAGO', 'MercadoPago'), ('OTRO', 'Otro')], default='EFECTIVO', help_text='Método utilizado para el pago', max_length=20),
        ),
    ]
