# Generated by Django 5.2.6 on 2025-11-26 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Nombre del archivo de backup', max_length=255)),
                ('file_path', models.TextField(help_text='Ruta del archivo en Supabase Storage')),
                ('file_size', models.BigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automático')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el backup (null si es automático)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Backup',
                'verbose_name_plural': 'Registros de Backups',
                'ordering': ['-created_at'],
            },
        ),
    ]
