# Generated by Django 5.2.6 on 2025-11-27 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_schedule', models.CharField(choices=[('daily', 'Diario'), ('every_12h', 'Cada 12 horas'), ('every_6h', 'Cada 6 horas'), ('weekly', 'Semanal')], default='daily', help_text='Frecuencia de backups automáticos', max_length=20)),
                ('backup_time', models.TimeField(default='02:00:00', help_text='Hora para ejecutar backups (formato 24h)')),
                ('retention_days', models.IntegerField(default=30, help_text='Días para mantener backups antes de eliminarlos')),
                ('is_active', models.BooleanField(default=True, help_text='Si los backups automáticos están activados')),
                ('last_backup_at', models.DateTimeField(blank=True, help_text='Fecha del último backup automático', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_configs_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Backup',
                'verbose_name_plural': 'Configuraciones de Backup',
            },
        ),
    ]
