# Generated by Django 5.2.6 on 2025-11-06 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='Email. Se usará para el login.', max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('ODONTOLOGO', 'Odontólogo'), ('PACIENTE', 'Paciente')], default='PACIENTE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='PerfilOdontologo',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_odontologo', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('cedulaProfesional', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('experienciaProfesional', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Perfil Odontólogo',
                'verbose_name_plural': 'Perfiles Odontólogos',
            },
        ),
        migrations.CreateModel(
            name='PerfilPaciente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_paciente', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Perfil Paciente',
                'verbose_name_plural': 'Perfiles Pacientes',
            },
        ),
    ]
