# Generated by Django 5.2.6 on 2025-11-07 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la especialidad odontológica', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la especialidad', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si la especialidad está activa para ser asignada')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='perfilodontologo',
            name='especialidad',
            field=models.ForeignKey(blank=True, help_text='Especialidad odontológica del profesional', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odontologos', to='usuarios.especialidad'),
        ),
    ]
