# Generated by Django 5.2.6 on 2025-11-06 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilOdontologo',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_odontologo', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('cedulaProfesional', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('experienciaProfesional', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Perfil Odontólogo',
                'verbose_name_plural': 'Perfiles Odontólogos',
            },
        ),
        migrations.CreateModel(
            name='PerfilPaciente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_paciente', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Perfil Paciente',
                'verbose_name_plural': 'Perfiles Pacientes',
            },
        ),
    ]
