# Generated by Django 5.2.6 on 2025-11-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_especialidad_alter_perfilodontologo_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ci',
            field=models.CharField(blank=True, help_text='Número de cédula de identidad o documento de identificación', max_length=20, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no especificar')], help_text='Sexo del usuario', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True),
        ),
    ]
