# Generated by Django 5.2.6 on 2025-11-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_ci_usuario_sexo_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Token de Firebase Cloud Messaging para notificaciones push', max_length=255, null=True),
        ),
    ]
