# Generated by Django 5.2.6 on 2025-11-07 15:47

import django.db.models.deletion
import historial_clinico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tratamientos', '0004_presupuesto_itempresupuesto_and_more'),
        ('usuarios', '0003_usuario_ci_usuario_sexo_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='historial_clinico', serialize=False, to='usuarios.perfilpaciente')),
                ('antecedentes_medicos', models.TextField(blank=True, help_text='Antecedentes médicos generales del paciente', null=True)),
                ('alergias', models.TextField(blank=True, help_text='Alergias conocidas del paciente', null=True)),
                ('medicamentos_actuales', models.TextField(blank=True, help_text='Medicamentos que el paciente toma actualmente', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Historial Clínico',
                'verbose_name_plural': 'Historiales Clínicos',
            },
        ),
        migrations.CreateModel(
            name='EpisodioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.CharField(help_text='Motivo principal de la consulta', max_length=255)),
                ('diagnostico', models.TextField(blank=True, help_text='Diagnóstico realizado en esta consulta', null=True)),
                ('descripcion_procedimiento', models.TextField(blank=True, help_text='Detalle de lo que se realizó en esta visita', null=True)),
                ('notas_privadas', models.TextField(blank=True, help_text='Notas solo visibles para el personal médico', null=True)),
                ('item_plan_tratamiento', models.ForeignKey(blank=True, help_text='Ítem del plan de tratamiento que se completó en esta visita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodios_asociados', to='tratamientos.itemplantratamiento')),
                ('odontologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodios_atendidos', to='usuarios.perfilodontologo')),
                ('historial_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='historial_clinico.historialclinico')),
            ],
            options={
                'verbose_name': 'Episodio de Atención',
                'verbose_name_plural': 'Episodios de Atención',
                'ordering': ['-fecha_atencion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del documento', max_length=255)),
                ('archivo', models.FileField(help_text='Archivo del documento clínico', upload_to=historial_clinico.models.subir_documento_paciente)),
                ('tipo_documento', models.CharField(choices=[('RADIOGRAFIA', 'Radiografía'), ('FOTOGRAFIA', 'Fotografía'), ('LABORATORIO', 'Examen de Laboratorio'), ('CONSENTIMIENTO', 'Consentimiento Informado'), ('RECETA', 'Receta Médica'), ('INFORME', 'Informe Médico'), ('OTRO', 'Otro')], default='OTRO', help_text='Tipo de documento clínico', max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('historial_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='historial_clinico.historialclinico')),
            ],
            options={
                'verbose_name': 'Documento Clínico',
                'verbose_name_plural': 'Documentos Clínicos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_snapshot', models.DateTimeField(auto_now_add=True)),
                ('estado_piezas', models.JSONField(default=dict, help_text='Estado detallado de cada pieza dental en formato JSON')),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales sobre este odontograma', null=True)),
                ('historial_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontogramas', to='historial_clinico.historialclinico')),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
                'ordering': ['-fecha_snapshot'],
            },
        ),
    ]
