# Generated by Django 5.2.6 on 2025-11-14 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_clinico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoclinico',
            name='episodio',
            field=models.ForeignKey(blank=True, help_text='Episodio de atención al que pertenece este documento (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='historial_clinico.episodioatencion'),
        ),
    ]
