# Generated by Django 5.2.6 on 2025-11-27 08:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0003_cita_pagada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, help_text='Comentario adicional del paciente', null=True)),
                ('puntualidad', models.IntegerField(blank=True, help_text='Calificación de puntualidad (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('trato', models.IntegerField(blank=True, help_text='Calificación del trato recibido (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('limpieza', models.IntegerField(blank=True, help_text='Calificación de limpieza e higiene (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('notificacion_enviada_at', models.DateTimeField(blank=True, null=True)),
                ('cita', models.OneToOneField(help_text='Cita que está siendo valorada', on_delete=django.db.models.deletion.CASCADE, related_name='valoracion', to='agenda.cita')),
                ('odontologo', models.ForeignKey(help_text='Odontólogo que recibe la valoración', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(help_text='Paciente que realiza la valoración', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'db_table': 'valoraciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['odontologo', '-created_at'], name='valoracione_odontol_0eb2e3_idx'), models.Index(fields=['paciente', '-created_at'], name='valoracione_pacient_236ce4_idx'), models.Index(fields=['calificacion'], name='valoracione_calific_069af5_idx')],
            },
        ),
    ]
